### ISSUE TITLE
Directory structure needs updating?

### ISSUE THREAD

**Issue by pedros007** [TDG-Platform/docs#1]
I could not get the Dockerfile to `ADD * /src/`.  I think your directory structure needs to be updated as described here: http://serverfault.com/a/666154/12294

**Comment by kstamatiou** [comment]
I'm not sure what this is and how it's related to this repo documentation. Closing.

**Comment by pedros007** [comment]
Good call on closing. This was from a long time ago when [the docs repo was very different from today](https://github.com/TDG-Platform/docs/tree/0c4e779ab72ffa501409c23e65f8e83853bc9ed2/file_count)!
